<?php
return [
	[
		'square' => 859,
		'name' => 'Волгоград',
		'phone' => '84',
		'image' => 'cities/images/1.png',
		'timezone' => 'UTC+04:00',
		'leader' => 'Гусева, Ирина Михайловна',
		'population' => 1016137,
	],
	[
		'square' => 596,
		'name' => 'Воронеж',
		'phone' => '47',
		'image' => 'cities/images/2.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Александр Викторович Гусев',
		'population' => 1032382,
	],
	[
		'square' => 468,
		'name' => 'Екатеринбург',
		'phone' => '34',
		'image' => 'cities/images/3.png',
		'timezone' => 'UTC+05:00',
		'leader' => 'Евгений Ройзман',
		'population' => 1386909,
	],
	[
		'square' => 425,
		'name' => 'Казань',
		'phone' => '84',
		'image' => 'cities/images/4.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Метшин, Ильсур Раисович',
		'population' => 1216965,
	],
	[
		'square' => 348,
		'name' => 'Красноярск',
		'phone' => '39',
		'image' => 'cities/images/5.png',
		'timezone' => 'UTC+07:00',
		'leader' => 'Акбулатов, Эдхам Шукриевич',
		'population' => 1066934,
	],
	[
		'square' => 2562,
		'name' => 'Москва',
		'phone' => '49',
		'image' => 'cities/images/6.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Сергей Семёнович Собянин',
		'population' => 12380664,
	],
	[
		'square' => 410,
		'name' => 'Нижний Новгород',
		'phone' => '83',
		'image' => 'cities/images/7.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Сорокин, Олег Валентинович',
		'population' => 1266871,
	],
	[
		'square' => 505,
		'name' => 'Новосибирск',
		'phone' => '38',
		'image' => 'cities/images/8.png',
		'timezone' => 'UTC+07:00',
		'leader' => 'Анатолий Евгеньевич Локоть',
		'population' => 1584138,
	],
	[
		'square' => 572,
		'name' => 'Омск',
		'phone' => '381',
		'image' => 'cities/images/9.png',
		'timezone' => 'UTC+06:00',
		'leader' => 'Двораковский, Вячеслав Викторович',
		'population' => 1178079,
	],
	[
		'square' => 799,
		'name' => 'Пермь',
		'phone' => '(+7) 34',
		'image' => 'cities/images/10.png',
		'timezone' => 'UTC+05:00',
		'leader' => 'Анатолий Юрьевич Маховиков',
		'population' => 3100,
	],
	[
		'square' => 348,
		'name' => 'Ростов-на-Дону',
		'phone' => '86',
		'image' => 'cities/images/11.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Неярохина, Зинаида Васильевна',
		'population' => 1119875,
	],
	[
		'square' => 541,
		'name' => 'Самара',
		'phone' => '84',
		'image' => 'cities/images/12.png',
		'timezone' => 'UTC+04:00',
		'leader' => 'Александр Борисович Фетисов',
		'population' => 1170910,
	],
	[
		'square' => 1439,
		'name' => 'Санкт-Петербург',
		'phone' => '81',
		'image' => 'cities/images/13.png',
		'timezone' => 'UTC+03:00',
		'leader' => 'Георгий Сергеевич Полтавченко',
		'population' => 5131942,
	],
	[
		'square' => 707,
		'name' => 'Уфа',
		'phone' => '34',
		'image' => 'cities/images/14.png',
		'timezone' => 'UTC+05:00',
		'leader' => 'Ялалов, Ирек Ишмухаметович',
		'population' => 1110976,
	],
	[
		'square' => 500,
		'name' => 'Челябинск',
		'phone' => '35',
		'image' => 'cities/images/15.png',
		'timezone' => 'UTC+05:00',
		'leader' => 'Евгений Николаевич Тефтелев',
		'population' => 1191994,
	],
];
